version: '3.9'

services:
  db:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_DB: capstoneDB
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - './backend/app/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql'